apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: monitoring
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: prometheus
    server: {{ .Values.cluster }}
  project: {{ .Values.project }}
  source:
    chart: kube-prometheus-stack
    helm:
      valueFiles:
      - values.yaml
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 9.4.8
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true

