apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: kube-system
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: kube-system
    server: {{ .Values.cluster }}
  project: {{ .Values.project }}
  source:
    chart: ingress-nginx/ingress-nginx
    helm:
      #parameters:
      #- name:  service.type
      #  value: LoadBalancer
      valueFiles:
      - values.yaml
    repoURL:  https://kubernetes.github.io/ingress-nginx
    targetRevision: 3.3.0
